/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.wlasnaaplikacja;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Michał
 */
public class WlasnaAplikacja extends javax.swing.JFrame {

    /**
     * Creates new form WlasnaAplikacja
     */
    public WlasnaAplikacja() {
        initComponents();
        md_jLabelAwatar.setIcon(new ImageIcon(AbsolutePathResources+"1Awatar.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        md_buttonGroupKolorTla = new javax.swing.ButtonGroup();
        md_jPanelMain1 = new javax.swing.JPanel();
        md_jLabelAwatar = new javax.swing.JLabel();
        md_jLabelLogin = new javax.swing.JLabel();
        md_jTextFieldLogin = new javax.swing.JTextField();
        md_jLabelHaslo = new javax.swing.JLabel();
        md_jPasswordFieldHaslo = new javax.swing.JPasswordField();
        md_jComboBoxAwatar = new javax.swing.JComboBox<>();
        md_jLabelWybierzAwatar = new javax.swing.JLabel();
        md_jLabelNapiszCosOSobie = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        md_jTextAreaInformacjeDoZapisu = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        md_jTextAreaInformacjeZZapisu = new javax.swing.JTextArea();
        md_jLabelInformacjeWczytane = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        md_jMenuPlik = new javax.swing.JMenu();
        md_jMenuItemZapisz = new javax.swing.JMenuItem();
        md_jMenuItemOtworz = new javax.swing.JMenuItem();
        md_jMenuItemZamknij = new javax.swing.JMenuItem();
        md_jMenuEdycja = new javax.swing.JMenu();
        md_jMenuZmienCzcionke = new javax.swing.JMenu();
        md_jMenuZmienTlo = new javax.swing.JMenu();
        md_jRadioButtonMenuItemSzary = new javax.swing.JRadioButtonMenuItem();
        md_jRadioButtonMenuItemCzerwony = new javax.swing.JRadioButtonMenuItem();
        md_jRadioButtonMenuItemNiebieski = new javax.swing.JRadioButtonMenuItem();
        md_jRadioButtonMenuItemZielony = new javax.swing.JRadioButtonMenuItem();
        md_jMenuOProgramie = new javax.swing.JMenu();
        md_jMenuItemOProgramie = new javax.swing.JMenuItem();
        md_jMenuItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        md_jPanelMain1.setBackground(new java.awt.Color(153, 153, 153));

        md_jLabelLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        md_jLabelLogin.setText("Login: ");

        md_jTextFieldLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        md_jLabelHaslo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        md_jLabelHaslo.setText("Hasło: ");

        md_jPasswordFieldHaslo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        md_jComboBoxAwatar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        md_jComboBoxAwatar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        md_jComboBoxAwatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jComboBoxAwatarActionPerformed(evt);
            }
        });

        md_jLabelWybierzAwatar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        md_jLabelWybierzAwatar.setText("Wybierz awatar: ");

        md_jLabelNapiszCosOSobie.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        md_jLabelNapiszCosOSobie.setText("Napisz coś o sobie: ");

        md_jTextAreaInformacjeDoZapisu.setColumns(20);
        md_jTextAreaInformacjeDoZapisu.setRows(5);
        jScrollPane1.setViewportView(md_jTextAreaInformacjeDoZapisu);

        md_jTextAreaInformacjeZZapisu.setColumns(20);
        md_jTextAreaInformacjeZZapisu.setRows(5);
        jScrollPane2.setViewportView(md_jTextAreaInformacjeZZapisu);

        md_jLabelInformacjeWczytane.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        md_jLabelInformacjeWczytane.setText("Informacje wczytane z pliku: ");

        javax.swing.GroupLayout md_jPanelMain1Layout = new javax.swing.GroupLayout(md_jPanelMain1);
        md_jPanelMain1.setLayout(md_jPanelMain1Layout);
        md_jPanelMain1Layout.setHorizontalGroup(
            md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(md_jPanelMain1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(md_jPanelMain1Layout.createSequentialGroup()
                        .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(md_jPanelMain1Layout.createSequentialGroup()
                                .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(md_jPanelMain1Layout.createSequentialGroup()
                                        .addComponent(md_jLabelLogin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(md_jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, md_jPanelMain1Layout.createSequentialGroup()
                                        .addComponent(md_jLabelHaslo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(md_jPasswordFieldHaslo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(md_jLabelWybierzAwatar)
                                .addGap(18, 18, 18)
                                .addComponent(md_jComboBoxAwatar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(md_jPanelMain1Layout.createSequentialGroup()
                                .addComponent(md_jLabelNapiszCosOSobie)
                                .addGap(173, 173, 173)
                                .addComponent(md_jLabelInformacjeWczytane)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(md_jLabelAwatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        md_jPanelMain1Layout.setVerticalGroup(
            md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_jPanelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(md_jPanelMain1Layout.createSequentialGroup()
                        .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(md_jLabelLogin)
                                .addComponent(md_jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(md_jLabelWybierzAwatar)
                                .addComponent(md_jComboBoxAwatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(md_jLabelHaslo)
                            .addComponent(md_jPasswordFieldHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(md_jLabelNapiszCosOSobie)
                            .addComponent(md_jLabelInformacjeWczytane)))
                    .addComponent(md_jLabelAwatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(md_jPanelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        md_jMenuPlik.setText("Plik");

        md_jMenuItemZapisz.setText("Zapisz");
        md_jMenuItemZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jMenuItemZapiszActionPerformed(evt);
            }
        });
        md_jMenuPlik.add(md_jMenuItemZapisz);

        md_jMenuItemOtworz.setText("Otwórz");
        md_jMenuItemOtworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jMenuItemOtworzActionPerformed(evt);
            }
        });
        md_jMenuPlik.add(md_jMenuItemOtworz);

        md_jMenuItemZamknij.setText("Zamknij");
        md_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jMenuItemZamknijActionPerformed(evt);
            }
        });
        md_jMenuPlik.add(md_jMenuItemZamknij);

        jMenuBar1.add(md_jMenuPlik);

        md_jMenuEdycja.setText("Edycja");

        md_jMenuZmienCzcionke.setText("Zmien czcionke");
        md_jMenuEdycja.add(md_jMenuZmienCzcionke);

        md_jMenuZmienTlo.setText("Zmien tło");

        md_buttonGroupKolorTla.add(md_jRadioButtonMenuItemSzary);
        md_jRadioButtonMenuItemSzary.setText("Szary");
        md_jRadioButtonMenuItemSzary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jRadioButtonMenuItemSzaryActionPerformed(evt);
            }
        });
        md_jMenuZmienTlo.add(md_jRadioButtonMenuItemSzary);

        md_buttonGroupKolorTla.add(md_jRadioButtonMenuItemCzerwony);
        md_jRadioButtonMenuItemCzerwony.setText("Czarwony");
        md_jRadioButtonMenuItemCzerwony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jRadioButtonMenuItemCzerwonyActionPerformed(evt);
            }
        });
        md_jMenuZmienTlo.add(md_jRadioButtonMenuItemCzerwony);

        md_buttonGroupKolorTla.add(md_jRadioButtonMenuItemNiebieski);
        md_jRadioButtonMenuItemNiebieski.setSelected(true);
        md_jRadioButtonMenuItemNiebieski.setText("Niebieski");
        md_jRadioButtonMenuItemNiebieski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jRadioButtonMenuItemNiebieskiActionPerformed(evt);
            }
        });
        md_jMenuZmienTlo.add(md_jRadioButtonMenuItemNiebieski);

        md_buttonGroupKolorTla.add(md_jRadioButtonMenuItemZielony);
        md_jRadioButtonMenuItemZielony.setText("Zielony");
        md_jRadioButtonMenuItemZielony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jRadioButtonMenuItemZielonyActionPerformed(evt);
            }
        });
        md_jMenuZmienTlo.add(md_jRadioButtonMenuItemZielony);

        md_jMenuEdycja.add(md_jMenuZmienTlo);

        jMenuBar1.add(md_jMenuEdycja);

        md_jMenuOProgramie.setText("O programie");

        md_jMenuItemOProgramie.setText("O programie");
        md_jMenuItemOProgramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_jMenuItemOProgramieActionPerformed(evt);
            }
        });
        md_jMenuOProgramie.add(md_jMenuItemOProgramie);

        md_jMenuItemHelp.setText("help");
        md_jMenuOProgramie.add(md_jMenuItemHelp);

        jMenuBar1.add(md_jMenuOProgramie);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(md_jPanelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(md_jPanelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int nrObrazka;
    
    private void md_jMenuItemZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jMenuItemZapiszActionPerformed
        try {
            FileWriter fw = new FileWriter(fileSettings);
            
            String login = md_jTextFieldLogin.getText();
            String oUzytkowniku = md_jTextAreaInformacjeDoZapisu.getText();
            int jakiObraz = nrObrazka;
            
            fw.write(""+login+";"+oUzytkowniku+";"+";"+jakiObraz);
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(WlasnaAplikacja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_md_jMenuItemZapiszActionPerformed

    private void md_jRadioButtonMenuItemSzaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jRadioButtonMenuItemSzaryActionPerformed
        md_jPanelMain1.setBackground(Color.gray);
    }//GEN-LAST:event_md_jRadioButtonMenuItemSzaryActionPerformed

    private void md_jRadioButtonMenuItemCzerwonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jRadioButtonMenuItemCzerwonyActionPerformed
        md_jPanelMain1.setBackground(Color.red);
    }//GEN-LAST:event_md_jRadioButtonMenuItemCzerwonyActionPerformed

    private void md_jRadioButtonMenuItemNiebieskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jRadioButtonMenuItemNiebieskiActionPerformed
        md_jPanelMain1.setBackground(Color.blue);
    }//GEN-LAST:event_md_jRadioButtonMenuItemNiebieskiActionPerformed

    private void md_jRadioButtonMenuItemZielonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jRadioButtonMenuItemZielonyActionPerformed
        md_jPanelMain1.setBackground(Color.green);
    }//GEN-LAST:event_md_jRadioButtonMenuItemZielonyActionPerformed

    private void md_jMenuItemOProgramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jMenuItemOProgramieActionPerformed
        JOptionPane.showMessageDialog(null, "Program ma na celu zapisywać zarejestrowanych użytkowników z wybranym awatarem, "
                + "pobierać od nich krótki opis, a następnie po wybrnaiu opcji otwórz wypisać go na arenie tekstowej", "O programie", HEIGHT);
    }//GEN-LAST:event_md_jMenuItemOProgramieActionPerformed

    private void md_jComboBoxAwatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jComboBoxAwatarActionPerformed
        javax.swing.JComboBox cb = (javax.swing.JComboBox)evt.getSource();
        int nr = cb.getSelectedIndex();
        String name = (String) cb.getSelectedItem();
        
        ImageIcon icon = new ImageIcon (AbsolutePathResources+name+".png");
        switch (nr){
            case 0:
                md_jLabelAwatar.setIcon(new javax.swing.ImageIcon(AbsolutePathResources+"1Awatar.png"));
                nrObrazka = 1;
                break;
            case 1:
                md_jLabelAwatar.setIcon(new javax.swing.ImageIcon(AbsolutePathResources+"2Awatar.png"));
                nrObrazka = 2;
                break;
            case 2:
                md_jLabelAwatar.setIcon(new javax.swing.ImageIcon(AbsolutePathResources+"3Awatar.png"));
                nrObrazka = 3;
                break;
            case 3:
                md_jLabelAwatar.setIcon(new javax.swing.ImageIcon(AbsolutePathResources+"4Awatar.png"));
                nrObrazka = 4;
                break;
        }
        
        
    }//GEN-LAST:event_md_jComboBoxAwatarActionPerformed

    private void md_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jMenuItemZamknijActionPerformed
        System.exit(1);
    }//GEN-LAST:event_md_jMenuItemZamknijActionPerformed

    private void md_jMenuItemOtworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_jMenuItemOtworzActionPerformed
        md_jLabelAwatar.setIcon(new javax.swing.ImageIcon(AbsolutePathResources+"1Awatar.png"));
        md_jLabelLogin.setText("");
        md_jLabelHaslo.setText("");
        md_jTextAreaInformacjeDoZapisu.setText("");
        md_jTextAreaInformacjeZZapisu.setText("");
        
        try {
            Scanner sc = new Scanner(fileSettings);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WlasnaAplikacja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String zapisanyLogin = "";
        int jakiObrazZZapisu;
        String InformzcjeDoZapisu = "";
        String InformacjeZZapisu = "";
        
        
        
    }//GEN-LAST:event_md_jMenuItemOtworzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WlasnaAplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WlasnaAplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WlasnaAplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WlasnaAplikacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WlasnaAplikacja().setVisible(true);
            }
        });
    }
    File fileSettings = new File("zapisDanych.txt");
    String AbsolutePathResources = "C:\\Users\\Michał\\Desktop\\Lekcje\\Desktopowe\\WlasnyProjekt\\WlasnaAplikacja\\src\\main\\java\\com\\mycompany\\wlasnaaplikacja\\resources\\";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup md_buttonGroupKolorTla;
    private javax.swing.JComboBox<String> md_jComboBoxAwatar;
    private javax.swing.JLabel md_jLabelAwatar;
    private javax.swing.JLabel md_jLabelHaslo;
    private javax.swing.JLabel md_jLabelInformacjeWczytane;
    private javax.swing.JLabel md_jLabelLogin;
    private javax.swing.JLabel md_jLabelNapiszCosOSobie;
    private javax.swing.JLabel md_jLabelWybierzAwatar;
    private javax.swing.JMenu md_jMenuEdycja;
    private javax.swing.JMenuItem md_jMenuItemHelp;
    private javax.swing.JMenuItem md_jMenuItemOProgramie;
    private javax.swing.JMenuItem md_jMenuItemOtworz;
    private javax.swing.JMenuItem md_jMenuItemZamknij;
    private javax.swing.JMenuItem md_jMenuItemZapisz;
    private javax.swing.JMenu md_jMenuOProgramie;
    private javax.swing.JMenu md_jMenuPlik;
    private javax.swing.JMenu md_jMenuZmienCzcionke;
    private javax.swing.JMenu md_jMenuZmienTlo;
    private javax.swing.JPanel md_jPanelMain1;
    private javax.swing.JPasswordField md_jPasswordFieldHaslo;
    private javax.swing.JRadioButtonMenuItem md_jRadioButtonMenuItemCzerwony;
    private javax.swing.JRadioButtonMenuItem md_jRadioButtonMenuItemNiebieski;
    private javax.swing.JRadioButtonMenuItem md_jRadioButtonMenuItemSzary;
    private javax.swing.JRadioButtonMenuItem md_jRadioButtonMenuItemZielony;
    private javax.swing.JTextArea md_jTextAreaInformacjeDoZapisu;
    private javax.swing.JTextArea md_jTextAreaInformacjeZZapisu;
    private javax.swing.JTextField md_jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
